spring:
  flyway:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/metasdb
    username: ${DB_USER:metas_user}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
          client:
            registration:
              google:
                client-id: ${GOOGLE_CLIENT_ID}
                client-secret: ${GOOGLE_CLIENT_SECRET}
                scope:
                  - openid
                  - profile
                  - email
            provider:
              google:
                issuer-uri: https://accounts.google.com

