name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build checkout
    - uses: actions/checkout@v4

    - name: Setup Java
    - uses: actions/setup-java@v3
        
    
      
